version: '3'

services:
  demo-springboot-container:
    image: demo-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/demo-springboot-container
    ports:
      - "8080-8100:8080"